// <auto-generated />
using System;
using DivingStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DivingStats.Migrations
{
    [DbContext(typeof(DiveDbContext))]
    [Migration("20240725000127_NullDates")]
    partial class NullDates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.32");

            modelBuilder.Entity("DivingStats.Data.Judge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("DivingStats.Models.Competition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("DivingStats.Models.Dive", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<decimal>("Board")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<decimal>("DD")
                        .HasColumnType("TEXT");

                    b.HasKey("ID", "Board");

                    b.ToTable("Dives");

                    b.HasData(
                        new
                        {
                            ID = "101A",
                            Board = 10m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "102A",
                            Board = 10m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "103A",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "104A",
                            Board = 10m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "101B",
                            Board = 10m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "102B",
                            Board = 10m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "103B",
                            Board = 10m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "104B",
                            Board = 10m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "105B",
                            Board = 10m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "107B",
                            Board = 10m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "112B",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "113B",
                            Board = 10m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "115B",
                            Board = 10m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "101C",
                            Board = 10m,
                            DD = 1.4m
                        },
                        new
                        {
                            ID = "102C",
                            Board = 10m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "103C",
                            Board = 10m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "104C",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "105C",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "107C",
                            Board = 10m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "109C",
                            Board = 10m,
                            DD = 3.5m
                        },
                        new
                        {
                            ID = "112C",
                            Board = 10m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "113C",
                            Board = 10m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "114C",
                            Board = 10m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "115C",
                            Board = 10m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "101A",
                            Board = 7.5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "102A",
                            Board = 7.5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "103A",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "101B",
                            Board = 7.5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "102B",
                            Board = 7.5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "103B",
                            Board = 7.5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "104B",
                            Board = 7.5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "105B",
                            Board = 7.5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "112B",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "113B",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "101C",
                            Board = 7.5m,
                            DD = 1.4m
                        },
                        new
                        {
                            ID = "102C",
                            Board = 7.5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "103C",
                            Board = 7.5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "104C",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "105C",
                            Board = 7.5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "107C",
                            Board = 7.5m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "112C",
                            Board = 7.5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "113C",
                            Board = 7.5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "114C",
                            Board = 7.5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "115C",
                            Board = 7.5m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "101A",
                            Board = 5m,
                            DD = 1.4m
                        },
                        new
                        {
                            ID = "102A",
                            Board = 5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "103A",
                            Board = 5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "101B",
                            Board = 5m,
                            DD = 1.3m
                        },
                        new
                        {
                            ID = "102B",
                            Board = 5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "103B",
                            Board = 5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "104B",
                            Board = 5m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "105B",
                            Board = 5m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "112B",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "113B",
                            Board = 5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "101C",
                            Board = 5m,
                            DD = 1.2m
                        },
                        new
                        {
                            ID = "102C",
                            Board = 5m,
                            DD = 1.4m
                        },
                        new
                        {
                            ID = "103C",
                            Board = 5m,
                            DD = 1.4m
                        },
                        new
                        {
                            ID = "104C",
                            Board = 5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "105C",
                            Board = 5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "107C",
                            Board = 5m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "112C",
                            Board = 5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "113C",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "201A",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "202A",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "203A",
                            Board = 10m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "204A",
                            Board = 10m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "205A",
                            Board = 10m,
                            DD = 3.3m
                        },
                        new
                        {
                            ID = "201B",
                            Board = 10m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "202B",
                            Board = 10m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "203B",
                            Board = 10m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "204B",
                            Board = 10m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "205B",
                            Board = 10m,
                            DD = 2.9m
                        },
                        new
                        {
                            ID = "212B",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "201C",
                            Board = 10m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "202C",
                            Board = 10m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "203C",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "204C",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "205C",
                            Board = 10m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "207C",
                            Board = 10m,
                            DD = 3.3m
                        },
                        new
                        {
                            ID = "212C",
                            Board = 10m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "213C",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "201A",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "202A",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "203A",
                            Board = 7.5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "204A",
                            Board = 7.5m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "201B",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "202B",
                            Board = 7.5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "203B",
                            Board = 7.5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "204B",
                            Board = 7.5m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "205B",
                            Board = 7.5m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "212B",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "201C",
                            Board = 7.5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "202C",
                            Board = 7.5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "203C",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "204C",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "205C",
                            Board = 7.5m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "207C",
                            Board = 7.5m,
                            DD = 3.4m
                        },
                        new
                        {
                            ID = "212C",
                            Board = 7.5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "213C",
                            Board = 7.5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "201A",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "202A",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "203A",
                            Board = 5m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "201B",
                            Board = 5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "202B",
                            Board = 5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "203B",
                            Board = 5m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "204B",
                            Board = 5m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "212B",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "201C",
                            Board = 5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "202C",
                            Board = 5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "203C",
                            Board = 5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "204C",
                            Board = 5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "205C",
                            Board = 5m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "212C",
                            Board = 5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "301A",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "302A",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "303A",
                            Board = 10m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "301B",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "302B",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "303B",
                            Board = 10m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "304B",
                            Board = 10m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "305B",
                            Board = 10m,
                            DD = 2.9m
                        },
                        new
                        {
                            ID = "301C",
                            Board = 10m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "302C",
                            Board = 10m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "303C",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "304C",
                            Board = 10m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "305C",
                            Board = 10m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "307C",
                            Board = 10m,
                            DD = 3.4m
                        },
                        new
                        {
                            ID = "312C",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "313C",
                            Board = 10m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "301A",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "302A",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "303A",
                            Board = 7.5m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "301B",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "302B",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "303B",
                            Board = 7.5m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "304B",
                            Board = 7.5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "305B",
                            Board = 7.5m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "301C",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "302C",
                            Board = 7.5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "303C",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "304C",
                            Board = 7.5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "305C",
                            Board = 7.5m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "312C",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "313C",
                            Board = 7.5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "301A",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "302A",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "303A",
                            Board = 5m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "301B",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "302B",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "303B",
                            Board = 5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "304B",
                            Board = 5m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "312B",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "301C",
                            Board = 5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "302C",
                            Board = 5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "303C",
                            Board = 5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "304C",
                            Board = 5m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "305C",
                            Board = 5m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "312C",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "401A",
                            Board = 10m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "401B",
                            Board = 10m,
                            DD = 1.4m
                        },
                        new
                        {
                            ID = "402B",
                            Board = 10m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "403B",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "404B",
                            Board = 10m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "405B",
                            Board = 10m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "407B",
                            Board = 10m,
                            DD = 3.5m
                        },
                        new
                        {
                            ID = "412B",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "413B",
                            Board = 10m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "401C",
                            Board = 10m,
                            DD = 1.3m
                        },
                        new
                        {
                            ID = "402C",
                            Board = 10m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "403C",
                            Board = 10m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "404C",
                            Board = 10m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "405C",
                            Board = 10m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "407C",
                            Board = 10m,
                            DD = 3.2m
                        },
                        new
                        {
                            ID = "412C",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "413C",
                            Board = 10m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "401A",
                            Board = 7.5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "401B",
                            Board = 7.5m,
                            DD = 1.4m
                        },
                        new
                        {
                            ID = "402B",
                            Board = 7.5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "403B",
                            Board = 7.5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "404B",
                            Board = 7.5m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "405B",
                            Board = 7.5m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "412B",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "401C",
                            Board = 7.5m,
                            DD = 1.3m
                        },
                        new
                        {
                            ID = "402C",
                            Board = 7.5m,
                            DD = 1.4m
                        },
                        new
                        {
                            ID = "403C",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "404C",
                            Board = 7.5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "405C",
                            Board = 7.5m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "407C",
                            Board = 7.5m,
                            DD = 3.4m
                        },
                        new
                        {
                            ID = "412C",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "413C",
                            Board = 7.5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "401A",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "401B",
                            Board = 5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "402B",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "403B",
                            Board = 5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "401C",
                            Board = 5m,
                            DD = 1.4m
                        },
                        new
                        {
                            ID = "402C",
                            Board = 5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "403C",
                            Board = 5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "404C",
                            Board = 5m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "405C",
                            Board = 5m,
                            DD = 3.1m
                        },
                        new
                        {
                            ID = "412C",
                            Board = 5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5111A",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5112A",
                            Board = 10m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "5211A",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5212A",
                            Board = 10m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "5311A",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5312A",
                            Board = 10m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "5411A",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5412A",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5111B",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5112B",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5152B",
                            Board = 10m,
                            DD = 2.9m
                        },
                        new
                        {
                            ID = "5154B",
                            Board = 10m,
                            DD = 3.3m
                        },
                        new
                        {
                            ID = "5253B",
                            Board = 10m,
                            DD = 3.4m
                        },
                        new
                        {
                            ID = "5353B",
                            Board = 10m,
                            DD = 3.4m
                        },
                        new
                        {
                            ID = "5411B",
                            Board = 10m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "5412B",
                            Board = 10m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "5421B",
                            Board = 10m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "5152C",
                            Board = 10m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "5154C",
                            Board = 10m,
                            DD = 3.1m
                        },
                        new
                        {
                            ID = "5253C",
                            Board = 10m,
                            DD = 3.2m
                        },
                        new
                        {
                            ID = "5353C",
                            Board = 10m,
                            DD = 3.2m
                        },
                        new
                        {
                            ID = "5421C",
                            Board = 10m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "5132D",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5134D",
                            Board = 10m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "5136D",
                            Board = 10m,
                            DD = 2.9m
                        },
                        new
                        {
                            ID = "5138D",
                            Board = 10m,
                            DD = 3.3m
                        },
                        new
                        {
                            ID = "5152D",
                            Board = 10m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "5154D",
                            Board = 10m,
                            DD = 3.1m
                        },
                        new
                        {
                            ID = "5231D",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5233D",
                            Board = 10m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "5235D",
                            Board = 10m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "5237D",
                            Board = 10m,
                            DD = 3.2m
                        },
                        new
                        {
                            ID = "5239D",
                            Board = 10m,
                            DD = 3.6m
                        },
                        new
                        {
                            ID = "5251D",
                            Board = 10m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "5253D",
                            Board = 10m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "5331D",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5333D",
                            Board = 10m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "5335D",
                            Board = 10m,
                            DD = 2.9m
                        },
                        new
                        {
                            ID = "5337D",
                            Board = 10m,
                            DD = 3.3m
                        },
                        new
                        {
                            ID = "5339D",
                            Board = 10m,
                            DD = 3.7m
                        },
                        new
                        {
                            ID = "5351D",
                            Board = 10m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "5353D",
                            Board = 10m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "5422D",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5432D",
                            Board = 10m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "5434D",
                            Board = 10m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "5111A",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5112A",
                            Board = 7.5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "5121A",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5211A",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5212A",
                            Board = 7.5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "5311A",
                            Board = 7.5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5312A",
                            Board = 7.5m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "5411A",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5412A",
                            Board = 7.5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5111B",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5112B",
                            Board = 7.5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5121B",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5152B",
                            Board = 7.5m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "5411B",
                            Board = 7.5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "5412B",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "5421B",
                            Board = 7.5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "5152C",
                            Board = 7.5m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "5421C",
                            Board = 7.5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "5132D",
                            Board = 7.5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5134D",
                            Board = 7.5m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "5136D",
                            Board = 7.5m,
                            DD = 2.9m
                        },
                        new
                        {
                            ID = "5138D",
                            Board = 7.5m,
                            DD = 3.3m
                        },
                        new
                        {
                            ID = "5152D",
                            Board = 7.5m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "5154D",
                            Board = 7.5m,
                            DD = 3.2m
                        },
                        new
                        {
                            ID = "5231D",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5233D",
                            Board = 7.5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "5235D",
                            Board = 7.5m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "5251D",
                            Board = 7.5m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "5331D",
                            Board = 7.5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5333D",
                            Board = 7.5m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "5335D",
                            Board = 7.5m,
                            DD = 2.9m
                        },
                        new
                        {
                            ID = "5422D",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5432D",
                            Board = 7.5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "5111A",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "5112A",
                            Board = 5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5121A",
                            Board = 5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5211A",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "5212A",
                            Board = 5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5311A",
                            Board = 5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5312A",
                            Board = 5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "5411A",
                            Board = 5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5412A",
                            Board = 5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "5111B",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "5112B",
                            Board = 5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5121B",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "5131B",
                            Board = 5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5411B",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "5412B",
                            Board = 5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5421B",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "5131C",
                            Board = 5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5421C",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "5121D",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "5122D",
                            Board = 5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5124D",
                            Board = 5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5132D",
                            Board = 5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "5134D",
                            Board = 5m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "5221D",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "5222D",
                            Board = 5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "5223D",
                            Board = 5m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "5225D",
                            Board = 5m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "5231D",
                            Board = 5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5233D",
                            Board = 5m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "5321D",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "5322D",
                            Board = 5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "5323D",
                            Board = 5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "5325D",
                            Board = 5m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "5422D",
                            Board = 5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "5432D",
                            Board = 5m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "600A",
                            Board = 10m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "611A",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "612A",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "621A",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "622A",
                            Board = 10m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "624A",
                            Board = 10m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "631A",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "612B",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "614B",
                            Board = 10m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "616B",
                            Board = 10m,
                            DD = 3.3m
                        },
                        new
                        {
                            ID = "621B",
                            Board = 10m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "622B",
                            Board = 10m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "623B",
                            Board = 10m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "624B",
                            Board = 10m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "626B",
                            Board = 10m,
                            DD = 3.5m
                        },
                        new
                        {
                            ID = "631B",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "632B",
                            Board = 10m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "612C",
                            Board = 10m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "614C",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "616C",
                            Board = 10m,
                            DD = 3m
                        },
                        new
                        {
                            ID = "622C",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "623C",
                            Board = 10m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "624C",
                            Board = 10m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "626C",
                            Board = 10m,
                            DD = 3.3m
                        },
                        new
                        {
                            ID = "631C",
                            Board = 10m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "632C",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "633C",
                            Board = 10m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "634C",
                            Board = 10m,
                            DD = 2.6m
                        },
                        new
                        {
                            ID = "636C",
                            Board = 10m,
                            DD = 3.3m
                        },
                        new
                        {
                            ID = "6122D",
                            Board = 10m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "6124D",
                            Board = 10m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "6142D",
                            Board = 10m,
                            DD = 3.1m
                        },
                        new
                        {
                            ID = "6144D",
                            Board = 10m,
                            DD = 3.5m
                        },
                        new
                        {
                            ID = "6221D",
                            Board = 10m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "6241D",
                            Board = 10m,
                            DD = 2.8m
                        },
                        new
                        {
                            ID = "6243D",
                            Board = 10m,
                            DD = 3.2m
                        },
                        new
                        {
                            ID = "600A",
                            Board = 7.5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "611A",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "612A",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "621A",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "622A",
                            Board = 7.5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "631A",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "612B",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "614B",
                            Board = 7.5m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "621B",
                            Board = 7.5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "622B",
                            Board = 7.5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "623B",
                            Board = 7.5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "624B",
                            Board = 7.5m,
                            DD = 2.7m
                        },
                        new
                        {
                            ID = "631B",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "632B",
                            Board = 7.5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "612C",
                            Board = 7.5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "614C",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "622C",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "623C",
                            Board = 7.5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "624C",
                            Board = 7.5m,
                            DD = 2.4m
                        },
                        new
                        {
                            ID = "631C",
                            Board = 7.5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "632C",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "633C",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "634C",
                            Board = 7.5m,
                            DD = 2.5m
                        },
                        new
                        {
                            ID = "6122D",
                            Board = 7.5m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "6221D",
                            Board = 7.5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "600A",
                            Board = 5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "611A",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "612A",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "621A",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "622A",
                            Board = 5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "612B",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "621B",
                            Board = 5m,
                            DD = 1.6m
                        },
                        new
                        {
                            ID = "622B",
                            Board = 5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "623B",
                            Board = 5m,
                            DD = 2.3m
                        },
                        new
                        {
                            ID = "631B",
                            Board = 5m,
                            DD = 1.7m
                        },
                        new
                        {
                            ID = "612C",
                            Board = 5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "614C",
                            Board = 5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "622C",
                            Board = 5m,
                            DD = 1.8m
                        },
                        new
                        {
                            ID = "623C",
                            Board = 5m,
                            DD = 2m
                        },
                        new
                        {
                            ID = "631C",
                            Board = 5m,
                            DD = 1.5m
                        },
                        new
                        {
                            ID = "632C",
                            Board = 5m,
                            DD = 1.9m
                        },
                        new
                        {
                            ID = "633C",
                            Board = 5m,
                            DD = 2.1m
                        },
                        new
                        {
                            ID = "6122D",
                            Board = 5m,
                            DD = 2.2m
                        },
                        new
                        {
                            ID = "6221D",
                            Board = 5m,
                            DD = 1.9m
                        });
                });

            modelBuilder.Entity("DivingStats.Models.Diver", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Divers");
                });

            modelBuilder.Entity("DivingStats.Models.IndividualDive", b =>
                {
                    b.Property<int>("DiverID")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("RoundID")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<decimal>("DiveBoard")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiveID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Judge1ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Judge2ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Judge3ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Judge4ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Judge5ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Judge6ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Judge7ID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Value1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value2")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value3")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value4")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value5")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value6")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value7")
                        .HasColumnType("TEXT");

                    b.HasKey("DiverID", "RoundID", "RoundNumber");

                    b.HasIndex("RoundID");

                    b.HasIndex("DiveID", "DiveBoard");

                    b.ToTable("IndividualDives");
                });

            modelBuilder.Entity("DivingStats.Models.Round", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CompetitionID");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<string>", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DivingStats.Models.IndividualDive", b =>
                {
                    b.HasOne("DivingStats.Models.Diver", "Diver")
                        .WithMany("IndividualDives")
                        .HasForeignKey("DiverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DivingStats.Models.Round", "Round")
                        .WithMany("IndividualDives")
                        .HasForeignKey("RoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DivingStats.Models.Dive", "Dive")
                        .WithMany("IndividualDives")
                        .HasForeignKey("DiveID", "DiveBoard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dive");

                    b.Navigation("Diver");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("DivingStats.Models.Round", b =>
                {
                    b.HasOne("DivingStats.Models.Competition", "Competition")
                        .WithMany("Rounds")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<string>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<string>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<string>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<string>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DivingStats.Models.Competition", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("DivingStats.Models.Dive", b =>
                {
                    b.Navigation("IndividualDives");
                });

            modelBuilder.Entity("DivingStats.Models.Diver", b =>
                {
                    b.Navigation("IndividualDives");
                });

            modelBuilder.Entity("DivingStats.Models.Round", b =>
                {
                    b.Navigation("IndividualDives");
                });
#pragma warning restore 612, 618
        }
    }
}
